### ISSUE TITLE
Lexer crash with using channels

### ISSUE THREAD

**Issue by amorimjuliana** [yar3333/antlr4-php-workspace#1]
Hi @yar3333 :)

@marcospassos and I are running some tests on existing grammars, and we noticed that the lexer fail to interpret simple grammars like the following one:

```antlr4
lexer grammar DemoLexer;

X
    : 'x' -> channel(HIDDEN)
;
```

```php
$lexer = new DemoLexer(CharStreams::fromString('x'));
$tokens = new CommonTokenStream($lexer);
$tokens->fill();
```

When parsing the input `x`, the lexer crashes with the following message: `Undefined offset: -1`.

We didn't have time to look at it in details yet.

**Comment by yar3333** [comment]
Thanks! Fixed.

**Comment by amorimjuliana** [comment]
@yar3333 the error still happens on the master running the [channel test](https://github.com/yar3333/antlr4-php-workspace/tree/master/tests/channel):

```
PHP Notice:  Undefined offset: -1 in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php on line 561

Notice: Undefined offset: -1 in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php on line 561
PHP Notice:  Trying to get property 'isPositionDependent' of non-object in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php on line 149

Notice: Trying to get property 'isPositionDependent' of non-object in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php on line 149
PHP Fatal error:  Uncaught Error: Call to a member function execute() on null in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php:154
Stack trace:
#0 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(390): Antlr4\Atn\LexerActionExecutor->execute(Object(generated\DemoLexer), Object(Antlr4\InputStream), 0)
#1 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(320): Antlr4\Atn\LexerATNSimulator->accept(Object(Antlr4\InputStream), Object(Antlr4\Atn\LexerActionExecutor), 0, 1, 1, 1)
#2 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(254): Antlr4\Atn\LexerATNSimulator->failOrAccept(Object(Antlr4\Atn\SimState), Object(Antlr4\InputStream), Object(Antlr4\Atn\OrderedATNConfigSet), -1)
#3 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(175): Antlr4\Atn\LexerATNSimulator->execATN(Object(Antlr4\InputStream), Object(Antlr4\ in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php on line 154

Fatal error: Uncaught Error: Call to a member function execute() on null in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php:154
Stack trace:
#0 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(390): Antlr4\Atn\LexerActionExecutor->execute(Object(generated\DemoLexer), Object(Antlr4\InputStream), 0)
#1 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(320): Antlr4\Atn\LexerATNSimulator->accept(Object(Antlr4\InputStream), Object(Antlr4\Atn\LexerActionExecutor), 0, 1, 1, 1)
#2 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(254): Antlr4\Atn\LexerATNSimulator->failOrAccept(Object(Antlr4\Atn\SimState), Object(Antlr4\InputStream), Object(Antlr4\Atn\OrderedATNConfigSet), -1)
#3 antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerATNSimulator.php(175): Antlr4\Atn\LexerATNSimulator->execATN(Object(Antlr4\InputStream), Object(Antlr4\ in antlr4-php-workspace/antlr4/runtime/Php/Atn/LexerActionExecutor.php on line 154
```

**Comment by yar3333** [comment]
Are you sure what you do pulling? Is "antlr4" subrepo have last commits from github?

**Comment by amorimjuliana** [comment]
Sorry, my fault. I forgot to update the submodule.
